version: "3.9"
services:
  spring-api-image:
    image: spring-api-restaurante
    container_name: spring-api-container
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/restaurante_pioriko?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 12345
    ports:
      - "8080:8080"
    networks:
      - spring-network
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0.40
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: 12345
      MYSQL_DATABASE: restaurante_pioriko
    ports:
      - "3307:3306"
    networks:
      - spring-network
    volumes:
      - mysql-volume:/var/lib/mysql

networks:
  spring-network:
volumes:
  mysql-volume:
